### PR TITLE
Include the flag saving/restoring macros

### PR DESCRIPTION
**Pull request by wferi**
And bring Xalan detection on par with the other libraries. I'm not sure of the point of the xalanMsg test (static linking?), so it's somewhat rudimentary, but should work as before.

### CODE REVIEW

**Comment by wferi** [comment]
I don't understand the role of the original xalanMsg test, because it's a pure presence test and nothing seems to depend on its result. I left in an inert symbol test as a reminder, though.

**Comment by scantor** [comment]
I'll commit the change, but regarding the pc file, shouldn't the Include/Libs lines specify the Xerces settings also? Certainly the headers if nothing else.

**Comment by scantor** [comment]
(And in fact the OpenSSL/NSS ones too, the headers that include those files are also public.)

**Comment by wferi** [comment]
The libs and includes of dependencies supporting pkg-config (Xerces, OpenSSL and NSS) are found by following the Requires(.private) lines of xml-security-c recursively:
~~~
$ PKG_CONFIG_PATH=. pkg-config --static --libs xml-security-c
-L/usr/local/lib -lxml-security-c -lxalan-c -lxerces-c -lcurl -lcrypto -ldl -pthread
~~~
(`--static`, because the shared objects contain their own dependency information; the include directories don't make this distinction but they are at the defaults, thus don't show anything in my setup).
It's possible that not everything should be declared private, it depends on the intended usage. Does xml-security-c "publish" symbols from any of its dependencies? Non-private dependencies appear in the non-static `--libs` output as well, making them "legitimately" available for the application as well (besides the library itself).

**Pull request closed without merging**
