### PR TITLE
Build system changes

### PR DESCRIPTION
**Pull request by wferi**
The main part is the switch to pkg-config for the libraries used and the better pkg-config support by this library. It shouldn't cause problems even for rather old platforms (`configure.ac` already assumes pkg-config>=0.27 due to `PKG_INSTALLDIR`), and Xerces, OpenSSL and NSS all provide usable pkg-config files.

The Pthreads removal is a totally unrelated thing, I don't understand how that got here at all. Is it supposed to protect from simultaneous usage from various threads?

Thanks for considering these patches.

Beyond this I saw a couple of signedness warnings and deprecations from OpenSSL, but otherwise the whole things builds fine.

### CODE REVIEW

**Comment by scantor** [comment]
This isn't a github-based project, so if you wish to open issues and submit patches, they should be done https://issues.apache.org/jira/projects/SANTUARIO

It's also extremely late in the cycle to consider anything that's going to affect the build, I was planning to do a release next week after years of waiting. I don't know that I'll have the time at this point, they'll need to wait for a future patch.

I don't understand the comment about threads. All library code should be built with the appropriate thread safety flags, and those flags make the code work safely whether it explicitly makes any calls into pthreads or not.

**Comment by scantor** [comment]
Most of this looks fine, I'd rather debug the header issues than leave them unfixed. I'll check those in momentarily. The only change that bothers me is to assume use of pkg-config really, and unfortunately the linking changes are too intricate to try and tease apart without breaking it.

If you do a version that maintains the "try pkg-config, fall back to --with options" approach but adjust the names of the various macros to line up with the other automake changes so it's consistent, I'd be ok with that, it's just not worth my time right now.

**Comment by scantor** [comment]
Per our email convo, I'm willing to take a shot and see if any of my actual builds break without using pkg-config for the tests, so I'll take in all but the pthread change.

**Comment by scantor** [comment]
These are all applied excepting the thread patch. If it builds clean on the Mac I'll probably take a shot at copying the change over to the Xalan dependency since I've been building it enabled there. Thx.

**Comment by wferi** [comment]
Thanks, closing this.
I don't think Xalan has upstream pkg-config support.
However, it should be added to Libs.private (and possibly Cflags) in `xml-security-c.pc` if it's found and used. I can give that a shot in a new PR.

**Pull request closed without merging**
